version: '3'

services:

    app:
        build: ./src
        restart: always
        env_file:
            - ./src/.env
        ports:
            - "8000:8000"
        volumes:
            - "./src/:/app/"
        command: bash -c "python ./projectRoot/manage.py migrate --noinput  &&
                                       python ./projectRoot/manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres:9.6
        restart: always
        volumes:
            - "postgres:/var/lib/postgresql/data"

volumes:
    postgres: